export const GET_HOT_TOPIC_DATA = 'GET_HOT_TOPIC_DATA';

export const GET_ARTICLE_DATA = 'GET_ARTICLE_DATA';

export const GET_MORE_ARTICLE_DATA = 'GET_MORE_ARTICLE_DATA';

export const GET_RECOMMEND_DATA = 'GET_RECOMMEND_DATA';

export const CHANGE_BACK_TOP_STATUS = 'CHANGE_BACK_TOP_STATUS';